name: Hprofile Action
on: push
jobs:
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Code Build
        run: mvn test

      - name: Checkstyle-analysise
        run: mvn checkstyle:checkstyle
      
      - name: Sonar-code-analysise
        uses: philips-software/sonar-scanner-action@1.4.0
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: pawar
          projectKey: pawar
          url: https://sonarcloud.io
          organization: pawar